spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/hometask?useUnicode=yes&characterEncoding=UTF-8
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
